version: "3.9"

services:
  api:
    build: .
    container_name: dublowcost
    restart: always

    ports:
      - "8085:8085"   # host:container

    volumes:
      - .:/app        # opcional (hot reload dev)

    environment:
      - PYTHONUNBUFFERED=1

    command: uvicorn src.main:app --host 0.0.0.0 --port 8085 --reload